---
__php_packages:
  - php7.3-common
  - php7.3-cli
  - php7.3-dev
  - php7.3-fpm
  - libpcre3-dev
  - php7.3-gd
  - php7.3-curl
  - php7.3-imap
  - php7.3-json
  - php7.3-opcache
  - php7.3-xml
  - php7.3-mbstring
  - php7.3-mysql
#  - php7.3-mcrypt
  - php7.3-zip
  - php-sqlite3
  - php-apcu
__php_webserver_daemon: "apache2"

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
__php_conf_paths:
  - /etc/php/7.3/fpm
  - /etc/php/7.3/apache2
  - /etc/php/7.3/cli

__php_extension_conf_paths:
  - /etc/php/7.3/fpm/conf.d
  - /etc/php/7.3/apache2/conf.d
  - /etc/php/7.3/cli/conf.d

__php_apc_conf_filename: 20-apcu.ini
__php_opcache_conf_filename: 05-opcache.ini
__php_fpm_daemon: php7.3-fpm
__php_fpm_conf_path: "/etc/php/7.3/fpm"
__php_fpm_pool_conf_path: "{{ __php_fpm_conf_path }}/pool.d/www.conf"

__php_fpm_pool_user: www-data
__php_fpm_pool_group: www-data
